apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloakdb
  name: keycloakdb
  namespace: default
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: keycloakdb
  type: ClusterIP