apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-pvc
  namespace: default
spec:
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce