apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kcdb
  name: kcdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcdb
  template:
    metadata:
      labels:
        app: kcdb
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: pass123
            - name: POSTGRES_USER
              value: keycloaddbuser
            - name: POSTGRES_DB
              value: dbkeycloak
          image: postgres:16
          name: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: kcdb-pvc
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: kcdb-pvc
          persistentVolumeClaim:
            claimName: kcdb-pvc