apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: 'quay.io/keycloak/keycloak:24.0'
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: kcdb.default.svc.cluster.local
            - name: DB_DATABASE
              value: dbkeycloak
            - name: DB_SCHEMA
              value: public
            - name: KC_DB_USERNAME
              value: keycloaddbuser
            - name: KC_DB_PASSWORD
              value: pass123
            - name: KEYCLOAK_USER
              value: keycloakuser
            - name: KEYCLOAK_PASSWORD
              value: keycloakpassword
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: apergisdev-keycloak.ddns.net
            - name: KC_PROXY
              value: edge
            - name: KC_HTTP_RELATIVE_PATH
              value: /
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: kc-pvc
      volumes:
        - name: kc-pvc
          persistentVolumeClaim:
            claimName: kc-pvc
