version: '3.9'

services:

  appdb:
    container_name: appdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: attendancedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - attendancedb_data:/var/lib/postgresql/data
    command: [ "docker-entrypoint.sh", "postgres", "-p", "5432" ]
    networks:
      - attendancecluster


  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - appdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://appdb:5432/attendancedb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8083:8083"
    networks:
      - attendancecluster

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakDb:5433/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakDb
    ports:
      - "8080:8080"
    networks:
      - attendancecluster

  keycloakDb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5433"
    volumes:
      - keycloakdb_data:/var/lib/postgresql/data
    command: ["docker-entrypoint.sh", "postgres", "-p", "5433"]
    networks:
      - attendancecluster

  kong:
    image: kong:latest
    restart: unless-stopped
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kongdb
      KONG_PG_USER: admin
      KONG_PG_PASSWORD: admin
      KONG_PG_DATABASE: kongdb
      KONG_PG_PORT: 5434
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kongdb
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - attendancecluster

  kongdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kongdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5434"
    volumes:
      - kongdb_data:/var/lib/postgresql/data
    networks:
      - attendancecluster
    command: ["docker-entrypoint.sh", "postgres", "-p", "5434"]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI
    networks:
      - attendancecluster

  frontend:
    build:
      context: ./attendance-system-fe/
      dockerfile: Dockerfile  # Replace with your frontend Dockerfile name if different
    restart: always
    ports:
      - "3000:3000"  # Adjust port as needed, this is for development
    networks:
      - attendancecluster

networks:
  attendancecluster:
    driver: bridge

volumes:
  attendancedb_data:
  keycloakdb_data:
  kong_data:
  kongdb_data:
