version: '3.7'
services:
  keycloak:
    build: ./keycloak
    ports:
      - "8080:8080"

  attendance-management:
    build: ./attendance-management
    ports:
      - "8081:8081"

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"