apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          command: ["kong", "migrations", "bootstrap"]
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: kongdb
            - name: KONG_PG_USER
              value: admin
            - name: KONG_PG_PASSWORD
              value: admin
            - name: KONG_PG_DATABASE
              value: kongdb
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8443
            - containerPort: 8444