apiVersion: apps/v1
kind: Deployment
metadata:
  name: kongdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kongdb
  template:
    metadata:
      labels:
        app: kongdb
    spec:
      containers:
        - name: kongdb
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: kongdb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: kongdb-pvc  # Updated volume name
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: kongdb-pvc  # Define the volume
          persistentVolumeClaim:
            claimName: kongdb-pvc  # Reference the PVC created above
