apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdb-data-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Adjust storage size as needed
