apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdb
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb
  template:
    metadata:
      labels:
        app: appdb
    spec:
      containers:
        - name: appdb
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: attendancedb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: appdb-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: appdb-data
          persistentVolumeClaim:
            claimName: appdb-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: appdb
  namespace: app
spec:
  selector:
    app: appdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
