apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb
  template:
    metadata:
      labels:
        app: appdb
    spec:
      containers:
        - name: appdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: attendancedb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
          volumeMounts:
            - name: appdb-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: appdb-data
          persistentVolumeClaim:
            claimName: appdb-data-pvc
