GNU nano 6.2                                                                                                    appdb-pvc.yaml                                                                                                             apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdb-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi






